# Generated by Django 2.2.7 on 2019-11-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=225)),
                ('question', models.TextField(max_length=3000)),
                ('pub_date', models.DateField(auto_now=True)),
                ('topic', models.ManyToManyField(to='topic.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=3000)),
                ('likes', models.IntegerField()),
                ('pub_date', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
    ]
